### ISSUE TITLE
Basic Architecture Diagram

### ISSUE THREAD

**Issue by renuka-srishti** [airavata-courses/Viyad#1]
In the group meeting, we come up with this basic design. Please free to share your input.

![Architecture_Design](https://user-images.githubusercontent.com/23609304/150874923-dc42c180-73d4-403c-8a76-52922b0c68d4.jpg)

**Comment by saiprasad-rane** [comment]
This is basic architecture diagram for our application. Here we are going to use an API gateway(subject to change) which will be used by client to make API calls. The API gateway will act as a middleware which will fetch the data from other microservices. The other microservices are Authentication Service, Data Fetch service and persistence service. The authentication service will take care of all the authentication process of the application. The data fetch service will fetch the data from AWS and the metadata will process it and send back to API gateway. The persistence service will save the instance of the data fetched by the user when user tries to save it.
