### ISSUE TITLE
Data base connection issue: PostgreSQL to Auth service

### ISSUE THREAD

**Issue by renuka-srishti** [airavata-courses/Viyad#105]

**Comment by ratchahan-anbarasan** [comment]
Hi,
Ideally the database services needs to be deployed prior to deploying your micro-services if you are using kubernetes. 
If not the services CrashLoopback but restarts always.I found a work around using initcontainers that would do a health check on the db service before deploying them. 

You can refer to the deployment yaml files from the link below
https://github.com/airavata-courses/vulcan/tree/develop/kubernetes.
