### ISSUE TITLE
Project Setup - Peer Review (SuperNova)

### ISSUE THREAD

**Issue by sanket1211996** [airavata-courses/Viyad#98]

**Comment by sanket1211996** [comment]
Frontend Microservice - Pull and Run. Working Perfectly

**Comment by sanket1211996** [comment]
Persistence Microservice - Pull and did docker compose up. Working Perfectly

**Comment by sanket1211996** [comment]
Login Authentication Microservice - Pull and Run. Working Perfectly

**Comment by sanket1211996** [comment]
API Gateway - Pull and Run. Working Perfectly

**Comment by sanket1211996** [comment]
<img width="1057" alt="Screen Shot 2022-01-19 at 11 52 21 PM" src="https://user-images.githubusercontent.com/24473558/153336281-9a573120-676b-48f1-b809-f4c159fbcceb.png">


Good Jobs Guyz

**Comment by sanket1211996** [comment]
<img width="1590" alt="Screen Shot 2022-02-09 at 11 20 31 PM" src="https://user-images.githubusercontent.com/24473558/153336551-f2691969-2fdd-482f-93db-fc099cd30eee.png">


Good Job Fellow Developers. 
Sanket Darwante
Team SuperNova

**Comment by renuka-srishti** [comment]
Thank you so much detailed testing and tried our system. I really appreciate it.
