### ISSUE TITLE
Project review (DCoders)

### ISSUE THREAD

**Issue by vinayakasg18** [airavata-courses/Viyad#99]
- Local run instructions are straightforward and easy to follow.
- Plot is taking time
- Looks like the token is not passed onto other Microservices.
- Good work overall.

**Comment by renuka-srishti** [comment]
Thank you so much for your feedback. I really appreciate it.
Yes we have generated the token, but not using right now. We are planning to pass to all other microservices in next project.
Regarding plot, also for this we will improve in next project. Right now we just focused on basic microservice architecture learning.
